package com.example.ui.localization

import androidx.compose.runtime.staticCompositionLocalOf

enum class StudioLanguage(
    val code: String,
    val nativeName: String,
    val flagLabel: String,
    val isRtl: Boolean = false
) {
    EN("en", "English", "EN", false),
    AR("ar", "العربية", "عربي", true),
    ES("es", "Español", "ES", false),
    FR("fr", "Français", "FR", false),
    ID("id", "Bahasa Indonesia", "ID", false),
    RU("ru", "Русский", "RU", false)
}

data class StudioStrings(
    val appTitle: String,
    val appSubtitle: String,
    val lowLatencyBadge: String,
    val originalAudio: String,
    val vocalOnly: String,
    val karaokeMode: String,
    val customMix: String,
    val isolationStrength: String,
    val tabNeuralVocal: String,
    val tabPitchTempo: String,
    val tabWebImport: String,
    val tabExportMp4: String,
    val tabLibraryPresets: String,
    val neuralArchitectureTitle: String,
    val neuralArchitectureSub: String,
    val performanceModeTitle: String,
    val cpuThreadsTitle: String,
    val chunkedOfflineExtract: String,
    val extractVocalsNow: String,
    val extractingProgress: String,
    val stemMixerTitle: String,
    val vocalStemLabel: String,
    val instrumentalStemLabel: String,
    val acousticFiltersTitle: String,
    val pitchShiftTitle: String,
    val tempoControlTitle: String,
    val fxTargetTitle: String,
    val syncVideoTempo: String,
    val resetBtn: String,
    val webImportTitle: String,
    val webImportSubtitle: String,
    val pasteUrlHint: String,
    val probeStreamBtn: String,
    val probingStatus: String,
    val availableStreamsTitle: String,
    val downloadQueueTitle: String,
    val loadIntoPlayerBtn: String,
    val cancelBtn: String,
    val exportVideoTitle: String,
    val exportVideoSubtitle: String,
    val exportFileNameHint: String,
    val deleteOriginalAfterExport: String,
    val startExportBtn: String,
    val shareExportedBtn: String,
    val mediaLibraryTitle: String,
    val openLocalFileBtn: String,
    val scanDeviceMediaBtn: String,
    val savedPresetsTitle: String,
    val saveCurrentPresetBtn: String
)

object StudioTranslations {
    fun forLanguage(lang: StudioLanguage): StudioStrings = when (lang) {
        StudioLanguage.EN -> StudioStrings(
            appTitle = "VocalCut Pro+",
            appSubtitle = "Neural Vocal Isolation • Pitch & Tempo • MP4 Export",
            lowLatencyBadge = "ZERO-LAG DSP",
            originalAudio = "Original Audio",
            vocalOnly = "Vocal Only",
            karaokeMode = "Instruments Only",
            customMix = "Custom Stem Mix",
            isolationStrength = "Vocal Isolation Strength",
            tabNeuralVocal = "Neural Vocal",
            tabPitchTempo = "Pitch & Tempo",
            tabWebImport = "Web & DL",
            tabExportMp4 = "Export MP4",
            tabLibraryPresets = "Library",
            neuralArchitectureTitle = "Neural Separation Architecture",
            neuralArchitectureSub = "On-device STFT spectral masking & harmonic-percussive separation",
            performanceModeTitle = "Operational Performance Mode",
            cpuThreadsTitle = "CPU Inference Threads",
            chunkedOfflineExtract = "High-Speed Offline Chunked Extraction",
            extractVocalsNow = "Run Offline Neural Pass",
            extractingProgress = "Processing STFT Chunks...",
            stemMixerTitle = "Dual Stem Volume Faders",
            vocalStemLabel = "Isolated Human Vocals",
            instrumentalStemLabel = "Background Music & Instruments",
            acousticFiltersTitle = "Studio Acoustic EQ & Reverb",
            pitchShiftTitle = "Pitch Shift (Key Transpose)",
            tempoControlTitle = "Tempo / Time Stretch",
            fxTargetTitle = "DSP Effect Routing Target",
            syncVideoTempo = "Sync Video",
            resetBtn = "Reset",
            webImportTitle = "Web Media Prober & Stream Importer",
            webImportSubtitle = "Inspect YouTube, TikTok, Vimeo, Dailymotion, HLS (.m3u8) & Direct MP4",
            pasteUrlHint = "Paste video or stream URL (4s fast probe)...",
            probeStreamBtn = "Probe Stream",
            probingStatus = "Probing manifest (4s max timeout)...",
            availableStreamsTitle = "Detected Resolutions & Audio Streams",
            downloadQueueTitle = "Multitask Background Download Manager",
            loadIntoPlayerBtn = "Load in Player",
            cancelBtn = "Cancel",
            exportVideoTitle = "Pipelined MP4 Video Export (Instruments Muted)",
            exportVideoSubtitle = "Remuxes video stream with isolated vocal & DSP audio track",
            exportFileNameHint = "Output filename (Full Arabic & Unicode supported)",
            deleteOriginalAfterExport = "Automatically delete original source file after verified export",
            startExportBtn = "Export Vocal-Only MP4",
            shareExportedBtn = "Share via FileProvider",
            mediaLibraryTitle = "Local Media, Device Storage & Studio Presets",
            openLocalFileBtn = "Pick Media",
            scanDeviceMediaBtn = "Scan Device",
            savedPresetsTitle = "Saved Studio Profiles",
            saveCurrentPresetBtn = "Save Preset"
        )

        StudioLanguage.AR -> StudioStrings(
            appTitle = "VocalCut Pro+",
            appSubtitle = "عزل الصوت البشري • تغيير الطبقة والسرعة • تصدير MP4",
            lowLatencyBadge = "معالجة فورية",
            originalAudio = "الصوت الأصلي",
            vocalOnly = "صوت بشري فقط",
            karaokeMode = "موسيقى فقط (كاريوكي)",
            customMix = "مكسر مخصص",
            isolationStrength = "قوة عزل الصوت البشري (كتم الموسيقى)",
            tabNeuralVocal = "عزل الصوت",
            tabPitchTempo = "الطبقة والسرعة",
            tabWebImport = "الويب والتحميل",
            tabExportMp4 = "تصدير MP4",
            tabLibraryPresets = "المكتبة",
            neuralArchitectureTitle = "نموذج الذكاء الاصطناعي لفصل الصوت",
            neuralArchitectureSub = "عزل طيفي مباشر على الجهاز بدون إنترنت أو سحابة",
            performanceModeTitle = "وضع الأداء وجودة المعالجة",
            cpuThreadsTitle = "أنوية المعالج (CPU Threads)",
            chunkedOfflineExtract = "الاستخراج المسبق فائق السرعة (Offline Chunked)",
            extractVocalsNow = "بدء الاستخراج الكامل الآن",
            extractingProgress = "جاري معالجة المقاطع الصوتية...",
            stemMixerTitle = "التحكم بمستوى المسارات المنفصلة",
            vocalStemLabel = "المسار الصوتي البشري (Vocals)",
            instrumentalStemLabel = "الموسيقى والإيقاع الخلفي",
            acousticFiltersTitle = "موازن الصوت والصدى الاحترافي",
            pitchShiftTitle = "تغيير طبقة الصوت (Pitch Shift)",
            tempoControlTitle = "تغيير السرعة والإيقاع (Tempo)",
            fxTargetTitle = "توجيه التأثيرات الصوتية",
            syncVideoTempo = "مزامنة الفيديو",
            resetBtn = "إعادة ضبط",
            webImportTitle = "استيراد وسائط الويب وفحص الروابط",
            webImportSubtitle = "يدعم YouTube و TikTok و Vimeo و Dailymotion و HLS (.m3u8)",
            pasteUrlHint = "الصق رابط الفيديو أو البث المباشر هنا...",
            probeStreamBtn = "فحص الرابط",
            probingStatus = "جاري فحص الجودات المتاحة (مهلة 4 ثوانٍ)...",
            availableStreamsTitle = "الجودات والمسارات المتاحة للتحميل",
            downloadQueueTitle = "مدير التحميل المتعدد في الخلفية",
            loadIntoPlayerBtn = "تشغيل الآن",
            cancelBtn = "إلغاء",
            exportVideoTitle = "تصدير فيديو MP4 (مع كتم الموسيقى)",
            exportVideoSubtitle = "دمج الفيديو الأصلي مع الصوت المعزول بدقة عالية",
            exportFileNameHint = "اسم الملف (يدعم اللغة العربية والرموز بالكامل)",
            deleteOriginalAfterExport = "حذف الملف الأصلي تلقائياً بعد التحقق من نجاح التصدير",
            startExportBtn = "تصدير فيديو MP4 بدون موسيقى",
            shareExportedBtn = "مشاركة الملف فوراً",
            mediaLibraryTitle = "مكتبة الوسائط والملفات المحفوظة",
            openLocalFileBtn = "فتح ملف",
            scanDeviceMediaBtn = "فحص الجهاز",
            savedPresetsTitle = "البروفايلات الصوتية المحفوظة",
            saveCurrentPresetBtn = "حفظ الإعدادات"
        )

        StudioLanguage.ES -> StudioStrings(
            appTitle = "VocalCut Pro+",
            appSubtitle = "Aislamiento Vocal Neural • Tono y Tempo • Exportar MP4",
            lowLatencyBadge = "CERO LATENCIA",
            originalAudio = "Audio Original",
            vocalOnly = "Solo Voz",
            karaokeMode = "Instrumental",
            customMix = "Mezcla Stem",
            isolationStrength = "Fuerza de Aislamiento Vocal",
            tabNeuralVocal = "Voz Neural",
            tabPitchTempo = "Tono y Tempo",
            tabWebImport = "Web y Descargas",
            tabExportMp4 = "Exportar MP4",
            tabLibraryPresets = "Biblioteca",
            neuralArchitectureTitle = "Arquitectura de Separación Neural",
            neuralArchitectureSub = "Enmascaramiento espectral STFT en el dispositivo",
            performanceModeTitle = "Modo de Rendimiento Operativo",
            cpuThreadsTitle = "Hilos de Inferencia CPU",
            chunkedOfflineExtract = "Extracción Offline de Alta Velocidad",
            extractVocalsNow = "Extraer Voz Offline",
            extractingProgress = "Procesando fragmentos STFT...",
            stemMixerTitle = "Mezclador de Volumen de Stems",
            vocalStemLabel = "Voz Humana Aislada",
            instrumentalStemLabel = "Música e Instrumentos de Fondo",
            acousticFiltersTitle = "Ecualizador Acústico y Reverb",
            pitchShiftTitle = "Cambio de Tono (Pitch Shift)",
            tempoControlTitle = "Tempo / Velocidad",
            fxTargetTitle = "Ruta de Destino DSP",
            syncVideoTempo = "Sincronizar Video",
            resetBtn = "Reiniciar",
            webImportTitle = "Importador Web y Analizador de Streams",
            webImportSubtitle = "Soporta YouTube, TikTok, Vimeo, Dailymotion, HLS (.m3u8)",
            pasteUrlHint = "Pegar enlace de video o stream...",
            probeStreamBtn = "Analizar URL",
            probingStatus = "Analizando stream (máx 4s)...",
            availableStreamsTitle = "Resoluciones y Audio Disponibles",
            downloadQueueTitle = "Gestor de Descargas Multitarea",
            loadIntoPlayerBtn = "Cargar en Reproductor",
            cancelBtn = "Cancelar",
            exportVideoTitle = "Exportación de Video MP4 (Sin Instrumentos)",
            exportVideoSubtitle = "Remuxea el video con la pista vocal aislada",
            exportFileNameHint = "Nombre del archivo (Soporte Unicode y Árabe)",
            deleteOriginalAfterExport = "Eliminar archivo original tras verificar exportación",
            startExportBtn = "Exportar MP4 Solo Voz",
            shareExportedBtn = "Compartir MP4",
            mediaLibraryTitle = "Biblioteca Multimedia y Presets",
            openLocalFileBtn = "Abrir Archivo",
            scanDeviceMediaBtn = "Escanear",
            savedPresetsTitle = "Perfiles de Audio Guardados",
            saveCurrentPresetBtn = "Guardar Preset"
        )

        StudioLanguage.FR -> StudioStrings(
            appTitle = "VocalCut Pro+",
            appSubtitle = "Isolation Vocale Neurale • Pitch & Tempo • Export MP4",
            lowLatencyBadge = "ZÉRO LATENCE",
            originalAudio = "Audio Original",
            vocalOnly = "Voix Seule",
            karaokeMode = "Instrumental",
            customMix = "Mix Personnalisé",
            isolationStrength = "Force d'Isolation Vocale",
            tabNeuralVocal = "Voix Neurale",
            tabPitchTempo = "Pitch & Tempo",
            tabWebImport = "Web & Téléch.",
            tabExportMp4 = "Export MP4",
            tabLibraryPresets = "Médias",
            neuralArchitectureTitle = "Architecture de Séparation Neurale",
            neuralArchitectureSub = "Masquage spectral STFT local sans serveur cloud",
            performanceModeTitle = "Mode de Performance",
            cpuThreadsTitle = "Threads CPU d'Inférence",
            chunkedOfflineExtract = "Extraction Hors-Ligne Haute Vitesse",
            extractVocalsNow = "Lancer l'Extraction",
            extractingProgress = "Traitement des blocs STFT...",
            stemMixerTitle = "Mixeur de Stems Audio",
            vocalStemLabel = "Voix Humaine Isolée",
            instrumentalStemLabel = "Musique & Instruments",
            acousticFiltersTitle = "Égaliseur Acoustique & Réverb",
            pitchShiftTitle = "Transposition Tonalité (Pitch)",
            tempoControlTitle = "Tempo / Vitesse",
            fxTargetTitle = "Cible de Routage DSP",
            syncVideoTempo = "Sync Vidéo",
            resetBtn = "Réinit.",
            webImportTitle = "Importateur Web & Analyseur de Flux",
            webImportSubtitle = "Inspecte YouTube, TikTok, Vimeo, Dailymotion, HLS (.m3u8)",
            pasteUrlHint = "Coller le lien vidéo ou flux...",
            probeStreamBtn = "Analyser Flux",
            probingStatus = "Inspection du manifeste (4s max)...",
            availableStreamsTitle = "Résolutions & Flux Audio Détectés",
            downloadQueueTitle = "Gestionnaire de Téléchargements Multitâche",
            loadIntoPlayerBtn = "Charger",
            cancelBtn = "Annuler",
            exportVideoTitle = "Export Vidéo MP4 (Instruments Coupés)",
            exportVideoSubtitle = "Remuxe la vidéo avec la piste vocale isolée",
            exportFileNameHint = "Nom du fichier (Support complet Arabe & Unicode)",
            deleteOriginalAfterExport = "Supprimer le fichier source après export vérifié",
            startExportBtn = "Exporter MP4 Voix Seule",
            shareExportedBtn = "Partager le MP4",
            mediaLibraryTitle = "Bibliothèque Média & Profils",
            openLocalFileBtn = "Ouvrir Fichier",
            scanDeviceMediaBtn = "Scanner",
            savedPresetsTitle = "Profils Audio Enregistrés",
            saveCurrentPresetBtn = "Sauvegarder"
        )

        StudioLanguage.ID -> StudioStrings(
            appTitle = "VocalCut Pro+",
            appSubtitle = "Isolasi Vokal Neural • Pitch & Tempo • Ekspor MP4",
            lowLatencyBadge = "TANPA JEDA",
            originalAudio = "Audio Asli",
            vocalOnly = "Hanya Vokal",
            karaokeMode = "Musik Saja",
            customMix = "Mix Kustom",
            isolationStrength = "Kekuatan Isolasi Vokal",
            tabNeuralVocal = "Vokal Neural",
            tabPitchTempo = "Pitch & Tempo",
            tabWebImport = "Web & Unduh",
            tabExportMp4 = "Ekspor MP4",
            tabLibraryPresets = "Pustaka",
            neuralArchitectureTitle = "Arsitektur Pemisahan Neural",
            neuralArchitectureSub = "Pemisahan spektral STFT langsung di perangkat",
            performanceModeTitle = "Mode Performa Operasional",
            cpuThreadsTitle = "Alokasi Thread CPU",
            chunkedOfflineExtract = "Ekstraksi Offline Kecepatan Tinggi",
            extractVocalsNow = "Ekstrak Vokal Sekarang",
            extractingProgress = "Memproses blok STFT...",
            stemMixerTitle = "Pengatur Volume Stem",
            vocalStemLabel = "Vokal Manusia Terisolasi",
            instrumentalStemLabel = "Musik & Instrumen Latar",
            acousticFiltersTitle = "Filter Akustik & Reverb Studio",
            pitchShiftTitle = "Pengubah Nada (Pitch Shift)",
            tempoControlTitle = "Tempo / Kecepatan",
            fxTargetTitle = "Target Efek DSP",
            syncVideoTempo = "Sinkron Video",
            resetBtn = "Reset",
            webImportTitle = "Impor Media Web & Pemeriksa Stream",
            webImportSubtitle = "Dukung YouTube, TikTok, Vimeo, Dailymotion, HLS (.m3u8)",
            pasteUrlHint = "Tempel tautan video atau stream...",
            probeStreamBtn = "Periksa URL",
            probingStatus = "Memeriksa resolusi (batas 4 detik)...",
            availableStreamsTitle = "Resolusi & Stream Audio Tersedia",
            downloadQueueTitle = "Manajer Unduhan Latar Belakang Multitugas",
            loadIntoPlayerBtn = "Muat ke Pemutar",
            cancelBtn = "Batal",
            exportVideoTitle = "Ekspor Video MP4 (Instrumen Dibisukan)",
            exportVideoSubtitle = "Gabungkan video asli dengan trek vokal terisolasi",
            exportFileNameHint = "Nama file (Mendukung penuh aksara Arab & Unicode)",
            deleteOriginalAfterExport = "Hapus file sumber asli secara otomatis setelah ekspor berhasil",
            startExportBtn = "Ekspor MP4 Hanya Vokal",
            shareExportedBtn = "Bagikan MP4",
            mediaLibraryTitle = "Pustaka Media & Preset Studio",
            openLocalFileBtn = "Pilih File",
            scanDeviceMediaBtn = "Pindai Perangkat",
            savedPresetsTitle = "Profil Audio Tersimpan",
            saveCurrentPresetBtn = "Simpan Preset"
        )

        StudioLanguage.RU -> StudioStrings(
            appTitle = "VocalCut Pro+",
            appSubtitle = "Нейро-изоляция вокала • Тон и Темп • Экспорт MP4",
            lowLatencyBadge = "БЕЗ ЗАДЕРЖКИ",
            originalAudio = "Оригинал",
            vocalOnly = "Только вокал",
            karaokeMode = "Минусовка",
            customMix = "Свой микс",
            isolationStrength = "Сила изоляции вокала (подавление музыки)",
            tabNeuralVocal = "Нейро-вокал",
            tabPitchTempo = "Тон и Темп",
            tabWebImport = "Веб и Загрузки",
            tabExportMp4 = "Экспорт MP4",
            tabLibraryPresets = "Медиатека",
            neuralArchitectureTitle = "Архитектура нейро-разделения",
            neuralArchitectureSub = "Локальное STFT-маскирование спектра на устройстве",
            performanceModeTitle = "Режим производительности",
            cpuThreadsTitle = "Потоки процессора (CPU Threads)",
            chunkedOfflineExtract = "Быстрое офлайн-извлечение вокала",
            extractVocalsNow = "Запустить офлайн-очистку",
            extractingProgress = "Обработка STFT-блоков...",
            stemMixerTitle = "Микшер громкости дорожек",
            vocalStemLabel = "Изолированный голос",
            instrumentalStemLabel = "Фоновая музыка и инструменты",
            acousticFiltersTitle = "Акустический эквалайзер и реверберация",
            pitchShiftTitle = "Изменение тональности (Pitch Shift)",
            tempoControlTitle = "Темп / Скорость воспроизведения",
            fxTargetTitle = "Маршрутизация эффектов DSP",
            syncVideoTempo = "Синхр. видео",
            resetBtn = "Сброс",
            webImportTitle = "Веб-импорт и анализ потоков",
            webImportSubtitle = "Поддержка YouTube, TikTok, Vimeo, Dailymotion, HLS (.m3u8)",
            pasteUrlHint = "Вставьте ссылку на видео или поток...",
            probeStreamBtn = "Проверить URL",
            probingStatus = "Анализ манифеста (таймаут 4 сек)...",
            availableStreamsTitle = "Доступные разрешения и аудиопотоки",
            downloadQueueTitle = "Многозадачный менеджер загрузок",
            loadIntoPlayerBtn = "В плеер",
            cancelBtn = "Отмена",
            exportVideoTitle = "Конвейерный экспорт MP4 (без музыки)",
            exportVideoSubtitle = "Сборка оригинального видео с очищенной дорожкой вокала",
            exportFileNameHint = "Имя файла (полная поддержка арабского и Unicode)",
            deleteOriginalAfterExport = "Автоматически удалить исходный файл после успешного экспорта",
            startExportBtn = "Экспортировать MP4 (только вокал)",
            shareExportedBtn = "Поделиться MP4",
            mediaLibraryTitle = "Медиатека устройства и пресеты",
            openLocalFileBtn = "Открыть файл",
            scanDeviceMediaBtn = "Сканировать",
            savedPresetsTitle = "Сохраненные аудио-профили",
            saveCurrentPresetBtn = "Сохранить"
        )
    }
}

val LocalStudioStrings = staticCompositionLocalOf {
    StudioTranslations.forLanguage(StudioLanguage.EN)
}
